# Generated by Django 4.1.5 on 2023-01-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_accesorio2_comentario_delete_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio2',
            name='imagenAccesorio',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
