# Generated by Django 4.1.5 on 2023-01-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_accesorio2_accesorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio2',
            name='accesorio',
            field=models.CharField(choices=[('teclado', 'teclados'), ('mouse', 'mouses'), ('auricular', 'auriculares')], max_length=15),
        ),
        migrations.AlterField(
            model_name='accesorio2',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
