# Generated by Django 4.1.5 on 2023-01-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_accesorio2_accesorio_alter_accesorio2_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio2',
            name='imagenAccesorio',
        ),
        migrations.AlterField(
            model_name='accesorio2',
            name='accesorio',
            field=models.CharField(choices=[('teclado', 'Teclados'), ('mouse', 'Mouses'), ('auricular', 'Auriculares')], max_length=15),
        ),
    ]
