# Generated by Django 4.1.5 on 2023-01-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_remove_accesorio2_imagenaccesorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio2',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
